services:

  web:
    image: nginx:latest
    container_name: climweb-ingestor_web
    restart: ${RESTART_POLICY}
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - pg-tileserv
    ports:
      - 443
      - ${APP_PORT}:80
    profiles: [production]

  backend:
    container_name: climweb-ingestor_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - DOCKER_COMPOSE_WAIT_PLATFORM_SUFFIX=${DOCKER_COMPOSE_WAIT_PLATFORM_SUFFIX:-}
    restart: ${RESTART_POLICY}
    environment:
      - DEBUG=False
      - WAIT_HOSTS=climweb-ingestor_db:5432
      - WAIT_TIMEOUT=60
      - SQLALCHEMY_DATABASE_URI=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - FLASK_APP=climweb-ingestorhydro/__init__.py
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8001:8001
    profiles: [production]

  db:
    image: ${DB_IMAGE:-postgis/postgis:15-master}
    container_name: climweb-ingestor_db
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432

  pg-tileserv:
    image: pramsey/pg_tileserv:latest
    container_name: climweb-ingestor_pg_tileserv
    restart: ${RESTART_POLICY}
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 7800

volumes:
  postgres_data:
